import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import bcrypt from "bcryptjs";
import { notifyAllMasters } from "@/lib/notifications/create";
import { buildAgreementPdf } from "@/lib/contracts/agreement-pdf";
import { uploadContractFile } from "@/lib/supabase/storage";
import { writeAuditLog } from "@/lib/audit/log";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface RedeemBody {
  token?: unknown;
  password?: unknown;
  legalBusinessName?: unknown;
  dba?: unknown;
  businessType?: unknown;
  ein?: unknown;
  businessPhone?: unknown;
  website?: unknown;
  addressStreet?: unknown;
  addressCity?: unknown;
  addressState?: unknown;
  addressZip?: unknown;
  ownerFullName?: unknown;
  ownerPhone?: unknown;
  ownerTitle?: unknown;
  bankName?: unknown;
  accountHolderName?: unknown;
  routingNumber?: unknown;
  accountNumber?: unknown;
  accountType?: unknown;
  monthlyVolume?: unknown;
  averageTicket?: unknown;
  mccCode?: unknown;
  agreementAccepted?: unknown;
}

function asString(v: unknown): string | null {
  if (typeof v !== "string") return null;
  const trimmed = v.trim();
  return trimmed.length === 0 ? null : trimmed;
}

async function uploadAndRecordAgreement(args: {
  merchantId: string;
  userId: string;
  userEmail: string;
  applicationId: string;
  pdfBytes: Uint8Array;
  legalBusinessName: string;
}): Promise<string> {
  const { randomUUID } = await import("crypto");
  const uniqueId = randomUUID().replace(/-/g, "").slice(0, 16);
  const safeName = args.legalBusinessName.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 60);
  const fileName = `master-services-agreement-${safeName}-${uniqueId}.pdf`;

  const result = await uploadContractFile({
    merchantId: args.merchantId,
    fileName,
    mimeType: "application/pdf",
    body: args.pdfBytes,
    uniqueId,
  });

  const row = await prisma.contract.create({
    data: {
      merchantId: args.merchantId,
      fileName,
      mimeType: "application/pdf",
      sizeBytes: args.pdfBytes.length,
      storagePath: result.storagePath,
      docType: "master_services_agreement",
      uploadedById: args.userId,
      uploadedByEmail: args.userEmail,
      uploadedByRole: "merchant",
      notes: "Automatically generated at onboarding submission.",
    },
  });

  await writeAuditLog({
    actor: { id: args.userId, email: args.userEmail, role: "merchant" },
    action: "contract.upload",
    targetType: "Contract",
    targetId: row.id,
    merchantId: args.merchantId,
    metadata: {
      fileName,
      mimeType: "application/pdf",
      sizeBytes: args.pdfBytes.length,
      docType: "master_services_agreement",
      autoGenerated: true,
      applicationId: args.applicationId,
    },
  });

  return row.id;
}

export async function POST(request: Request) {
  let body: RedeemBody;
  try {
    body = (await request.json()) as RedeemBody;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const token = asString(body.token);
  const password = typeof body.password === "string" ? body.password : "";

  if (!token) {
    return NextResponse.json({ error: "token required" }, { status: 400 });
  }
  if (password.length < 8) {
    return NextResponse.json(
      { error: "Password must be at least 8 characters" },
      { status: 400 }
    );
  }

  const invite = await prisma.merchantInvite.findUnique({ where: { token } });
  if (!invite) {
    return NextResponse.json({ error: "Invalid invitation" }, { status: 404 });
  }
  if (invite.status === "accepted") {
    return NextResponse.json(
      { error: "This invitation has already been used" },
      { status: 410 }
    );
  }
  if (invite.status === "revoked") {
    return NextResponse.json(
      { error: "This invitation was revoked" },
      { status: 410 }
    );
  }
  if (invite.expiresAt < new Date()) {
    await prisma.merchantInvite.update({
      where: { id: invite.id },
      data: { status: "expired" },
    });
    return NextResponse.json(
      { error: "This invitation has expired" },
      { status: 410 }
    );
  }

  const legalBusinessName = asString(body.legalBusinessName);
  const businessType = asString(body.businessType);
  const ein = asString(body.ein);
  const businessPhone = asString(body.businessPhone);
  const addressStreet = asString(body.addressStreet);
  const addressCity = asString(body.addressCity);
  const addressState = asString(body.addressState);
  const addressZip = asString(body.addressZip);
  const ownerFullName = asString(body.ownerFullName);
  const ownerPhone = asString(body.ownerPhone);
  const bankName = asString(body.bankName);
  const accountHolderName = asString(body.accountHolderName);
  const routingNumber = asString(body.routingNumber);
  const accountNumber = asString(body.accountNumber);
  const accountType = asString(body.accountType);
  const monthlyVolume = asString(body.monthlyVolume);
  const averageTicket = asString(body.averageTicket);
  const mccCode = asString(body.mccCode);

  const required = {
    legalBusinessName, businessType, ein, businessPhone,
    addressStreet, addressCity, addressState, addressZip,
    ownerFullName, ownerPhone,
    bankName, accountHolderName, routingNumber, accountNumber, accountType,
    monthlyVolume, averageTicket, mccCode,
  };
  for (const [k, v] of Object.entries(required)) {
    if (!v) {
      return NextResponse.json({ error: `${k} is required` }, { status: 400 });
    }
  }

  if (body.agreementAccepted !== true) {
    return NextResponse.json(
      { error: "Agreement must be accepted" },
      { status: 400 }
    );
  }

  const dba = asString(body.dba);
  const website = asString(body.website);
  const ownerTitle = asString(body.ownerTitle) ?? "Owner";

  const existingUser = await prisma.user.findUnique({
    where: { email: invite.email },
  });
  if (existingUser) {
    return NextResponse.json(
      { error: "Account already exists for this email" },
      { status: 409 }
    );
  }

  const hashedPassword = bcrypt.hashSync(password, 12);

  const result = await prisma.$transaction(async (tx) => {
    const user = await tx.user.create({
      data: {
        email: invite.email,
        password: hashedPassword,
        role: "merchant",
        approvalStatus: "pending",
      },
    });

    const application = await tx.merchantApplication.create({
      data: {
        userId: user.id,
        legalBusinessName: legalBusinessName!,
        dba,
        businessType: businessType!,
        ein: ein!,
        businessPhone: businessPhone!,
        website,
        addressStreet: addressStreet!,
        addressCity: addressCity!,
        addressState: addressState!,
        addressZip: addressZip!,
        ownerFullName: ownerFullName!,
        ownerEmail: invite.email,
        ownerPhone: ownerPhone!,
        ownerTitle,
        bankName: bankName!,
        accountHolderName: accountHolderName!,
        routingNumber: routingNumber!,
        accountNumber: accountNumber!,
        accountType: accountType!,
        monthlyVolume: monthlyVolume!,
        averageTicket: averageTicket!,
        mccCode: mccCode!,
        agreementAccepted: true,
        status: "submitted",
      },
    });

    await tx.merchantInvite.update({
      where: { id: invite.id },
      data: {
        status: "accepted",
        acceptedAt: new Date(),
        acceptedById: user.id,
        applicationId: application.id,
      },
    });

    return { user, application };
  });

  // Auto-copy onboarding agreement as PDF to merchant Contract storage.
  // Best-effort: failures are logged but don't break the redeem flow.
  let agreementContractId: string | null = null;
  try {
    const ipAddress =
      request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
      request.headers.get("x-real-ip") ??
      "unknown";
    const userAgent = request.headers.get("user-agent") ?? "unknown";

    const accountLast4 =
      typeof body.accountNumber === "string" && (body.accountNumber as string).length >= 4
        ? (body.accountNumber as string).slice(-4)
        : "----";

    const pdfBytes = buildAgreementPdf({
      submittedAt: new Date(),
      ipAddress,
      userAgent,
      applicationId: result.application.id,

      legalBusinessName: legalBusinessName!,
      dba,
      businessType: businessType!,
      ein: ein!,
      businessPhone: businessPhone!,

      addressStreet: addressStreet!,
      addressCity: addressCity!,
      addressState: addressState!,
      addressZip: addressZip!,

      ownerFullName: ownerFullName!,
      ownerEmail: invite.email,
      ownerPhone: ownerPhone!,
      ownerTitle: ownerTitle ?? "Owner",

      bankName: bankName!,
      accountHolderName: accountHolderName!,
      accountLast4,
      accountType: accountType!,
      routingNumber: routingNumber!,

      monthlyVolume: monthlyVolume!,
      averageTicket: averageTicket!,
      mccCode: mccCode!,
    });

    let merchantRow = await prisma.merchant.findUnique({
      where: { userId: result.user.id },
      select: { id: true },
    });

    if (!merchantRow) {
      merchantRow = await prisma.merchant.create({
        data: {
          userId: result.user.id,
          businessName: legalBusinessName!,
          email: invite.email,
          status: "pending",
        },
      });
    }

    agreementContractId = await uploadAndRecordAgreement({
      merchantId: merchantRow.id,
      userId: result.user.id,
      userEmail: invite.email,
      applicationId: result.application.id,
      pdfBytes,
      legalBusinessName: legalBusinessName!,
    });

    if (agreementContractId) {
      await prisma.merchantApplication.update({
        where: { id: result.application.id },
        data: { signedAgreementContractId: agreementContractId },
      });
    }
  } catch (e) {
    console.error("[REDEEM] Agreement PDF generation failed:", e);
  }

  try {
    await notifyAllMasters({
      category: "merchant",
      severity: "success",
      title: "Invite accepted",
      message: `${invite.businessName} (${invite.email}) accepted your invite and submitted their application.`,
      link: `/master/applications`,
      metadata: {
        inviteId: invite.id,
        merchantBusinessName: invite.businessName,
        merchantEmail: invite.email,
        applicationId: result.application.id,
      },
    });
  } catch {
    // Notification failure should not break the redeem flow
  }

  return NextResponse.json({
    ok: true,
    applicationId: result.application.id,
    signedAgreementContractId: agreementContractId,
  });
}
