/**
 * Payroc cert test plan — seed data.
 *
 * Hardcoded from Matt Perry's "ReynaPay_Test_Cases.xlsx" spreadsheet
 * sent 2026-04-30. Source of truth for test case definitions used by
 * the /master/cert-tests runner.
 *
 * STATE (status, paymentId, notes, ranAt) is stored per-session in
 * the CertTestRun table. This file holds only definitions.
 *
 * When new test cases are added (e.g., Apple Pay, Google Pay), append
 * to the appropriate sheet's array. Existing in-flight CertTestSessions
 * are NOT auto-updated — that's intentional, locks scope at session
 * creation time.
 */

export interface CertTestCaseDefinition {
  id: string;
  sheetName: "CNP" | "CP";
  sectionName: string;
  transactionType: string;
  scenario: string;
  expectedResult: string;
  required: boolean;
}

// CNP test cases — Hosted Fields / Card Not Present (all run via web checkout)
export const CNP_TEST_CASES: CertTestCaseDefinition[] = [
  // Hosted Fields: Credit Card Sale WITH singleUseToken
  {
    id: "cnp-hf-cc-sut-generate",
    sheetName: "CNP",
    sectionName: "Hosted Fields: Credit Card Sale WITH singleUseToken",
    transactionType: "Generate a Credit Card singleUseToken",
    scenario: "Generate a singleUseToken with Hosted Fields. Include CVV information in this request.",
    expectedResult: "Approved",
    required: true,
  },

  // Credit Card Sale NO Secure Token
  {
    id: "cnp-cc-nst-sale-approved",
    sheetName: "CNP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in this request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-nst-sale-decline-01",
    sheetName: "CNP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cnp-cc-nst-sale-avs-03",
    sheetName: "CNP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-nst-sale-cvv-04",
    sheetName: "CNP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-nst-sale-referral-02",
    sheetName: "CNP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Sale WITH Create Secure Token In Request
  {
    id: "cnp-cc-cst-sale-approved",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH Create Secure Token In Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in this request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-cst-sale-decline-01",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH Create Secure Token In Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cnp-cc-cst-sale-avs-03",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH Create Secure Token In Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-cst-sale-cvv-04",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH Create Secure Token In Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-cst-sale-referral-02",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH Create Secure Token In Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Sale WITH a Previously Created Secure Token
  {
    id: "cnp-cc-pst-sale-approved",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH a Previously Created Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in this request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-pst-sale-decline-01",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH a Previously Created Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cnp-cc-pst-sale-avs-03",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH a Previously Created Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-pst-sale-cvv-04",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH a Previously Created Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-pst-sale-referral-02",
    sheetName: "CNP",
    sectionName: "Credit Card Sale WITH a Previously Created Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Pre-Auth | Capture and NO Secure Token
  {
    id: "cnp-cc-preauth-nst-approved",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and NO Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in request. NOTE: Capture Must be tested to support Pre-Auth.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-nst-capture",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and NO Secure Token",
    transactionType: "Capture (Pre-Auth Completion)",
    scenario: "Capture your previously Pre-Authorized transaction.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-nst-decline-01",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and NO Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-nst-avs-03",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and NO Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-nst-cvv-04",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and NO Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-nst-referral-02",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and NO Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Pre-Auth | Capture and Create Secure Token
  {
    id: "cnp-cc-preauth-cst-approved",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and Create Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in request. NOTE: Capture Must be tested to support Pre-Auth.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-cst-capture",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and Create Secure Token",
    transactionType: "Capture (Pre-Auth Completion)",
    scenario: "Capture your previously Pre-Authorized transaction.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-cst-decline-01",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and Create Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-cst-avs-03",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and Create Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-cst-cvv-04",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and Create Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-cst-referral-02",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture and Create Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Pre-Auth | Capture WITH a Previously Created Secure Token
  {
    id: "cnp-cc-preauth-pst-approved",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture WITH a Previously Created Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in request. NOTE: Capture Must be tested to support Pre-Auth.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-pst-capture",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture WITH a Previously Created Secure Token",
    transactionType: "Capture (Pre-Auth Completion)",
    scenario: "Capture your previously Pre-Authorized transaction.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-pst-decline-01",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture WITH a Previously Created Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-pst-avs-03",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture WITH a Previously Created Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-pst-cvv-04",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture WITH a Previously Created Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-pst-referral-02",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture WITH a Previously Created Secure Token",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Pre-Auth | Capture (with ADJUST)
  {
    id: "cnp-cc-preauth-adjust-approved",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-adjust-adjust",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "ADJUST-Authorization",
    scenario: "Adjust a previously Processed Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09. NOTE: Capture Must be tested to support Pre-Auth.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-adjust-capture",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Capture (Pre-Auth Completion)",
    scenario: "Capture your previously Pre-Authorized transaction.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-preauth-adjust-decline-01",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-adjust-avs-03",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-adjust-cvv-04",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cnp-cc-preauth-adjust-referral-02",
    sheetName: "CNP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Void/Reverse and Refund
  {
    id: "cnp-cc-void-same-day",
    sheetName: "CNP",
    sectionName: "Credit Card Void/Reverse and Refund",
    transactionType: "Void/Reversal (Same Day)",
    scenario: "Process a void/reversal of a transaction. If supported through your integration, process this via the API. If supporting via Gateway Selfcare UI, please make the note 'via Gateway Selfcare UI'",
    expectedResult: "Void Complete",
    required: true,
  },
  {
    id: "cnp-cc-refund-next-day",
    sheetName: "CNP",
    sectionName: "Credit Card Void/Reverse and Refund",
    transactionType: "Refund (Next Day)",
    scenario: "Process a refund of a transaction previously submitted. If supported through your integration, process this via the API. If supporting via Gateway Selfcare UI, please make the note 'via Gateway Selfcare UI'",
    expectedResult: "Refund",
    required: true,
  },
  {
    id: "cnp-cc-unreferenced-refund",
    sheetName: "CNP",
    sectionName: "Credit Card Void/Reverse and Refund",
    transactionType: "Unreferenced Refund - Credit Card",
    scenario: "Process a credit card refund without any previous transaction",
    expectedResult: "Approved",
    required: true,
  },

  // CREATE a Credit Card Secure Token without Processing a Sale
  {
    id: "cnp-cc-token-create",
    sheetName: "CNP",
    sectionName: "CREATE a Credit Card Secure Token without Processing a Sale",
    transactionType: "Secure Token Creation",
    scenario: "Create a Token during a Sale or on its own. Include AVS and CVV information in request.",
    expectedResult: "Approved. Token in response.",
    required: true,
  },
  {
    id: "cnp-cc-token-update",
    sheetName: "CNP",
    sectionName: "CREATE a Credit Card Secure Token without Processing a Sale",
    transactionType: "Secure Token Update",
    scenario: "Process a sale using the previously created token.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-token-delete",
    sheetName: "CNP",
    sectionName: "CREATE a Credit Card Secure Token without Processing a Sale",
    transactionType: "Secure Token Delete",
    scenario: "Process a deletion of a previously created token.",
    expectedResult: "Approved",
    required: true,
  },

  // Credit Card Recurring Transaction
  {
    id: "cnp-cc-recurring-first",
    sheetName: "CNP",
    sectionName: "Credit Card Recurring Transaction",
    transactionType: "Recurring Sale - First Trans",
    scenario: "Sale with standingInstructions for 1st Trans",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-cc-recurring-subsequent",
    sheetName: "CNP",
    sectionName: "Credit Card Recurring Transaction",
    transactionType: "Recurring Sale - Subsequent Trans",
    scenario: "Sale with standingInstructions for additional Trans",
    expectedResult: "Approved",
    required: true,
  },

  // Hosted Fields: ACH Sale WITH singleUseToken
  {
    id: "cnp-hf-ach-sut-generate",
    sheetName: "CNP",
    sectionName: "Hosted Fields: ACH Sale WITH singleUseToken",
    transactionType: "Generate an ACH singleUseToken",
    scenario: "Generate a singleUseToken with Hosted Fields.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-hf-ach-sut-sale",
    sheetName: "CNP",
    sectionName: "Hosted Fields: ACH Sale WITH singleUseToken",
    transactionType: "Sale with singleUseToken",
    scenario: "Process a sale for any amount.",
    expectedResult: "Approved",
    required: true,
  },

  // ACH WITH NO Secure Token Generation
  {
    id: "cnp-ach-nst-sale",
    sheetName: "CNP",
    sectionName: "ACH WITH NO Secure Token Generation",
    transactionType: "ACH",
    scenario: "Process a sale using ACH as the payment method.",
    expectedResult: "Approved",
    required: true,
  },

  // ACH WITH Create Secure Token in Request
  {
    id: "cnp-ach-cst-sale",
    sheetName: "CNP",
    sectionName: "ACH WITH Create Secure Token in Request",
    transactionType: "ACH",
    scenario: "Process a sale using ACH as the payment method.",
    expectedResult: "Approved",
    required: true,
  },

  // ACH Void/Reverse and Refund
  {
    id: "cnp-ach-void-same-day",
    sheetName: "CNP",
    sectionName: "ACH Void/Reverse and Refund",
    transactionType: "Void/Reversal (Same Day)",
    scenario: "Process a void/reversal of a transaction. If supported through your integration, process this via the API. If supporting via Gateway Selfcare UI, please make the note 'via Gateway Selfcare UI'",
    expectedResult: "Void Complete",
    required: true,
  },
  {
    id: "cnp-ach-refund-7-days",
    sheetName: "CNP",
    sectionName: "ACH Void/Reverse and Refund",
    transactionType: "Refund (7 days later)",
    scenario: "Process a refund of a transaction previously submitted. If supported through your integration, process this via the API. If supporting via Gateway Selfcare UI, please make the note 'via Gateway Selfcare UI'",
    expectedResult: "Refund",
    required: true,
  },

  // CREATE an ACH Secure Token without Processing a Sale
  {
    id: "cnp-ach-token-create",
    sheetName: "CNP",
    sectionName: "CREATE an ACH Secure Token without Processing a Sale",
    transactionType: "Secure Token Creation",
    scenario: "Create a Token during a Sale or on its own.",
    expectedResult: "Approved. Token in response.",
    required: true,
  },
  {
    id: "cnp-ach-token-update",
    sheetName: "CNP",
    sectionName: "CREATE an ACH Secure Token without Processing a Sale",
    transactionType: "Secure Token Update",
    scenario: "Process an update to a previously created token.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-ach-token-delete",
    sheetName: "CNP",
    sectionName: "CREATE an ACH Secure Token without Processing a Sale",
    transactionType: "Secure Token Delete",
    scenario: "Process a deletion of a previously created token.",
    expectedResult: "Approved",
    required: true,
  },

  // ACH Subscription Transaction
  {
    id: "cnp-ach-recurring-first",
    sheetName: "CNP",
    sectionName: "ACH Subscription Transaction",
    transactionType: "Recurring Sale - First Trans",
    scenario: "Sale with standingInstructions for 1st Trans",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-ach-recurring-subsequent",
    sheetName: "CNP",
    sectionName: "ACH Subscription Transaction",
    transactionType: "Recurring Sale - Subsequent Trans",
    scenario: "Sale with standingInstructions for additional Trans",
    expectedResult: "Approved",
    required: true,
  },

  // Additional Charges with Payments
  {
    id: "cnp-surcharge-accept",
    sheetName: "CNP",
    sectionName: "Additional Charges with Payments",
    transactionType: "Reward Pay (Surcharging) Accept",
    scenario: "Process a sale noting the popup for the Fee. Accept the fee to process the sale",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cnp-surcharge-decline",
    sheetName: "CNP",
    sectionName: "Additional Charges with Payments",
    transactionType: "Reward Pay (Surcharging) Decline",
    scenario: "Process a sale noting the popup for the Fee. Decline the fee to verify transaction stops.",
    expectedResult: "Page Resets",
    required: true,
  },
  {
    id: "cnp-dual-pricing",
    sheetName: "CNP",
    sectionName: "Additional Charges with Payments",
    transactionType: "Consumer Choice (Dual Pricing)",
    scenario: "Process two sales with Consumer Choice. One with card as the payment method and one with ACH as the payment method.",
    expectedResult: "Approved, card and ACH will have different price based on the dual pricing settings.",
    required: true,
  },
  {
    id: "cnp-service-fee",
    sheetName: "CNP",
    sectionName: "Additional Charges with Payments",
    transactionType: "Service Fee (Convenience Fee)",
    scenario: "Process a sale with service fee's enabled. Note service fee in response.",
    expectedResult: "Approved, Service fee routed and applied.",
    required: true,
  },
];

// CP test cases — Card Present / Payroc Cloud (run via Pax A920 Pro terminal)
export const CP_TEST_CASES: CertTestCaseDefinition[] = [
  // Credit Card Sale NO Secure Token
  {
    id: "cp-cc-nst-sale-approved",
    sheetName: "CP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in this request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-nst-sale-decline-01",
    sheetName: "CP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cp-cc-nst-sale-avs-03",
    sheetName: "CP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-nst-sale-cvv-04",
    sheetName: "CP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-nst-sale-referral-02",
    sheetName: "CP",
    sectionName: "Credit Card Sale NO Secure Token",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Sale WITH Create Secure Token in Request
  {
    id: "cp-cc-cst-sale-approved",
    sheetName: "CP",
    sectionName: "Credit Card Sale WITH Create Secure Token in Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in this request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-cst-sale-decline-01",
    sheetName: "CP",
    sectionName: "Credit Card Sale WITH Create Secure Token in Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cp-cc-cst-sale-avs-03",
    sheetName: "CP",
    sectionName: "Credit Card Sale WITH Create Secure Token in Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-cst-sale-cvv-04",
    sheetName: "CP",
    sectionName: "Credit Card Sale WITH Create Secure Token in Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-cst-sale-referral-02",
    sheetName: "CP",
    sectionName: "Credit Card Sale WITH Create Secure Token in Request",
    transactionType: "Sale",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Pre-Auth | Capture
  {
    id: "cp-cc-preauth-approved",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture",
    transactionType: "Pre-Authorization",
    scenario: "Process a Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-preauth-capture",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture",
    transactionType: "Capture (Pre-Auth Completion)",
    scenario: "Capture your previously Pre-Authorized transaction.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-preauth-decline-01",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cp-cc-preauth-avs-03",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-preauth-cvv-04",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-preauth-referral-02",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Pre-Auth | Capture (with Adjust)
  {
    id: "cp-cc-preauth-adjust-approved",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09. Include AVS and CVV information in request.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-preauth-adjust-adjust",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "ADJUST-Authorization",
    scenario: "Adjust a previously Processed Pre-Authorization for an amount ending in .00, .05, .06, .07, .08, .09.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-preauth-adjust-capture",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Capture (Pre-Auth Completion)",
    scenario: "Capture your previously Pre-Authorized transaction.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-preauth-adjust-decline-01",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .01. General Decline Response",
    expectedResult: "Decline",
    required: true,
  },
  {
    id: "cp-cc-preauth-adjust-avs-03",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .03. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-preauth-adjust-cvv-04",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .04. May Decline depending on gateway settings",
    expectedResult: "Approve/Decline",
    required: true,
  },
  {
    id: "cp-cc-preauth-adjust-referral-02",
    sheetName: "CP",
    sectionName: "Credit Card Pre-Auth | Capture (with Adjust)",
    transactionType: "Pre-Authorization",
    scenario: "Process a sale for an amount ending in .02. Include AVS and CVV information in this request.",
    expectedResult: "Referral",
    required: true,
  },

  // Credit Card Void/Reverse and Refund
  {
    id: "cp-cc-void-same-day",
    sheetName: "CP",
    sectionName: "Credit Card Void/Reverse and Refund",
    transactionType: "Void/Reversal (Same Day)",
    scenario: "Process a void/reversal of a transaction. If supported through your integration, process this via the API. If supporting via Gateway Selfcare UI, please make the note 'via Gateway Selfcare UI'",
    expectedResult: "Void Complete",
    required: true,
  },
  {
    id: "cp-cc-refund-next-day",
    sheetName: "CP",
    sectionName: "Credit Card Void/Reverse and Refund",
    transactionType: "Refund (Next Day)",
    scenario: "Process a refund of a transaction previously submitted. If supported through your integration, process this via the API. If supporting via Gateway Selfcare UI, please make the note 'via Gateway Selfcare UI'",
    expectedResult: "Refund",
    required: true,
  },
  {
    id: "cp-cc-unreferenced-refund",
    sheetName: "CP",
    sectionName: "Credit Card Void/Reverse and Refund",
    transactionType: "Unreferenced Refund - Credit Card",
    scenario: "Process a credit card refund without any previous transaction",
    expectedResult: "Approved",
    required: true,
  },

  // Credit Card Sale ERROR TEST
  {
    id: "cp-cc-error-bad-card",
    sheetName: "CP",
    sectionName: "Credit Card Sale ERROR TEST",
    transactionType: "Sale",
    scenario: "Process a sale for any amount. Keyed BAD CARD entry.",
    expectedResult: "Card Error",
    required: true,
  },

  // CREATE a Credit Card Secure Token via Terminal
  {
    id: "cp-cc-token-create",
    sheetName: "CP",
    sectionName: "CREATE a Credit Card Secure Token via Terminal",
    transactionType: "Secure Token Creation",
    scenario: "Create a Token during a Sale or on its own. Include AVS and CVV information in request.",
    expectedResult: "Approved, token in response.",
    required: true,
  },
  {
    id: "cp-cc-token-sale",
    sheetName: "CP",
    sectionName: "CREATE a Credit Card Secure Token via Terminal",
    transactionType: "Secure Token Sale",
    scenario: "Process a sale using the previously created token.",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-cc-token-update",
    sheetName: "CP",
    sectionName: "CREATE a Credit Card Secure Token via Terminal",
    transactionType: "Secure Token Update",
    scenario: "Process a sale using the previously created token.",
    expectedResult: "Approved",
    required: true,
  },

  // Additional Transactions or Charges with Payments
  {
    id: "cp-surcharge-accept",
    sheetName: "CP",
    sectionName: "Additional Transactions or Charges with Payments",
    transactionType: "Reward Pay (Surcharging) Accept",
    scenario: "Process a sale noting the popup for the Fee. Accept the fee to process the sale",
    expectedResult: "Approved",
    required: true,
  },
  {
    id: "cp-surcharge-decline",
    sheetName: "CP",
    sectionName: "Additional Transactions or Charges with Payments",
    transactionType: "Reward Pay (Surcharging) Decline",
    scenario: "Process a sale noting the popup for the Fee. Decline the fee to verify device resets.",
    expectedResult: "Device Resets",
    required: true,
  },
  {
    id: "cp-dual-pricing",
    sheetName: "CP",
    sectionName: "Additional Transactions or Charges with Payments",
    transactionType: "Consumer Choice (Dual Pricing)",
    scenario: "Process two sales with Consumer Choice. One with card as the payment method and one with ACH as the payment method.",
    expectedResult: "Approved, card and ACH will have different price based on the dual pricing settings.",
    required: true,
  },
  {
    id: "cp-service-fee",
    sheetName: "CP",
    sectionName: "Additional Transactions or Charges with Payments",
    transactionType: "Service Fee (Convenience Fee)",
    scenario: "Process a sale with service fee's enabled. Note service fee in response.",
    expectedResult: "Approved, Service fee routed and applied.",
    required: true,
  },
];

export const ALL_TEST_CASES = [...CNP_TEST_CASES, ...CP_TEST_CASES];

// Aggregate stats helper
export function getTestCaseStats(): {
  total: number;
  cnp: number;
  cp: number;
  required: number;
  optional: number;
} {
  return {
    total: ALL_TEST_CASES.length,
    cnp: CNP_TEST_CASES.length,
    cp: CP_TEST_CASES.length,
    required: ALL_TEST_CASES.filter((t) => t.required).length,
    optional: ALL_TEST_CASES.filter((t) => !t.required).length,
  };
}
